name: "allcheckspassed"
description: "GitHub Action to check if all checks have passed on a specific commit"
author: "wechuli"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  commit_sha:
    description: "The commit sha that you want to check"
    required: false
  token:
    description: "The GitHub token to use for authentication"
    required: false
    default: ${{ github.token }}
  checks:
    description: "A comma separated list of checks to check"
    required: false
    default: "-1"
  checks_exclude:
    description: "A comma separated list of checks to exclude, if this checks fail,the action will not fail"
    required: false
    default: "-1"
  treat_skipped_as_passed:
    description: "If set to true, skipped checks will be treated as passed"
    required: false
    default: "true"
  create_check:
    description: "If set to true, the action will create it's own check on the commit, rather than the default created by GitHub Action. Must be a GitHub App token"
    required: false
    default: "false"
  include_commit_statuses:
    description: "If set to true, the action will include commit statuses in the check, checks and commit statuses have different APIs"
    required: false
    default: "true"
outputs:
  time:
    description: "Your output description here"

runs:
  using: node20
  main: dist/index.js
